environment_version: 1
credentials:
- type: aws
  id: FoqPFbneOKF6EEir
  description: 'aws read-only '
  access_key_id: AWS_ACCESS_KEY_ID
  secret_access_key: AWS_SECRET_ACCESS_KEY
  region: AWS_DEFAULT_REGION
- type: api-key
  id: r466MAnrT9Qu992I
  description: Code Ocean API
  key: API_KEY
  secret: API_SECRET
